name: Bug Report
description: File a bug report
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Minimal reproduction
      description: 10 lines of code or fewer that reproduce the bug.
      render: python
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Paste the output of `nvcc --version && gcc --version`
      render: shell
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / stack trace
      description: If applicable, paste the full error output.
      render: shell
